# Generated by Django 5.2.12 on 2026-04-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', help_text='Current status of the reservation.', max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True, help_text='When the reservation was made.')),
                ('released_at', models.DateTimeField(blank=True, help_text='When the locker was released.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locker', models.ForeignKey(help_text='The locker that is reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='lockers.locker')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
