# Generated by Django 5.2.12 on 2026-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.CharField(db_index=True, help_text='Unique locker identifier (e.g., "A-101").', max_length=20, unique=True)),
                ('location', models.CharField(help_text='Physical location of the locker.', max_length=255)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Size category of the locker.', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('deactivated', 'Deactivated')], db_index=True, default='available', help_text='Current status of the locker.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locker',
                'verbose_name_plural': 'Lockers',
                'db_table': 'lockers',
                'ordering': ['locker_number'],
            },
        ),
    ]
